---
- name: "Download Kibana's deb"
  when: kibana_install_type == 'remote'
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-amd64.deb"
    dest: "files/kibana-{{ kibana_version }}-amd64.deb"
    validate_certs: false
  register: download_kibana
  delegate_to: localhost
  until: download_kibana is succeeded
  tags: [download]

- name: Copy Kibana to managed node
  copy:
    src: "files/kibana-{{ kibana_version }}-amd64.deb"
    dest: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
    mode: 0755
